---
- name: Install hadoop
  hosts: vm
  become: yes
  remote_user: ubuntu
  tasks:
    - name: Copy contents from /home/ubuntu/hadoop to /opt/hadoop
      shell: rsync -a --chown=ubuntu:ubuntu /home/ubuntu/hadoop/ /opt/hadoop/
      become: true
    - name: Set JAVA_HOME based on architecture
      set_fact:
        java_home_path: "{{ '/usr/lib/jvm/java-11-openjdk-amd64' if ansible_architecture == 'x86_64' else '/usr/lib/jvm/java-11-openjdk-arm64' }}"
    - name: Append environment variables to .bashrc
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: "{{ item }}"
        state: present
      loop:
        - 'export HADOOP_HOME=/opt/hadoop'
        - 'export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin'
        - 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64'
    - name: Copy core-site.xml to instances
      copy:
        src: ../hadoop/core-site.xml
        dest: /opt/hadoop/etc/hadoop/core-site.xml
    - name: Copy hdfs-site.xml to instances
      copy:
        src: ../hadoop/hdfs-site.xml
        dest: /opt/hadoop/etc/hadoop/hdfs-site.xml
    - name: Copy yarn-site.xml to instances
      copy:
        src: ../hadoop/yarn-site.xml
        dest: /opt/hadoop/etc/hadoop/yarn-site.xml
    - name: Copy mapred-site.xml to instances
      copy:
        src: ../hadoop/mapred-site.xml
        dest: /opt/hadoop/etc/hadoop/mapred-site.xml