---
- name: Install VM dependencies and configurations
  hosts: vm
  become: yes
  remote_user: ubuntu
  tasks:
    - name: Replace sources.list
      copy:
        src: ./sources.list
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: '0644'
      when: replace_source == true
    - name: Update apt package cache
      apt:
        update_cache: yes
    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
    - name: Install OpenJDK 11 headless
      apt:
        name: openjdk-11-jdk-headless
        state: present
    - name: Copy hosts file to instances
      copy:
        src: ./hosts
        dest: /tmp/hosts
    - name: Append host file content to /etc/cloud/templates/hosts.debian.tmpl
      shell: cat /tmp/hosts >> /etc/cloud/templates/hosts.debian.tmpl
      become: yes