---
- name: Update and upgrade VMs packages
  hosts: vm
  become: yes
  remote_user: ubuntu
  tasks:
    - name: Replace sources.list
      copy:
        src: ./sources.list
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: '0644'
      when: replace_source == true
    - name: Update apt package cache
      apt:
        update_cache: yes
    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
    - name: Install OpenJDK 11 headless
      apt:
        name: openjdk-11-jdk-headless
        state: present
    # - name: Install Python2
    #   apt:
    #     name: python2
    #     state: present