---
- name: Install hadoop environment
  hosts: vm01
  remote_user: ubuntu
  tasks:
    - name: Add slave nodes to workers
      lineinfile:
        path: /opt/hadoop/etc/hadoop/workers
        line: "{{ item }}"
        create: no
      with_items: "{{ groups['vm'] | select('match', '^vm[0-9]+$') | map('extract', hostvars, 'inventory_hostname') | reject('equalto', 'vm01') | list }}"
    - name: Check if name node format
      stat:
        path: /opt/hadoop/hdfs/namenode/current
      register: name_node
    - name: Initialize name node
      shell: /opt/hadoop/bin/hdfs namenode -format
      when: not name_node.stat.exists
