---
- name: Install Apache Hive
  hosts: hadoop
  remote_user: ubuntu
  tasks:
    - name: Check if /opt/hive/RELEASE_NOTES.txt exists
      stat:
        path: /opt/hive/RELEASE_NOTES.txt
      register: hive_dir
    - name: Copy contents from /home/ubuntu/hive to /opt/hive
      shell: rsync -a --chown=ubuntu:ubuntu /home/ubuntu/hive/ /opt/hive/
      become: true
      when: not hive_dir.stat.exists
    - name: Append environment variables to .bashrc
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: "{{ item }}"
        state: present
      loop:
        - 'export HIVE_HOME=/opt/hive'
        - 'export PATH=$PATH:$HIVE_HOME/bin'
    - name: Copy mysql-connector-j-9.1.0.jar to hive
      ansible.builtin.command:
        cmd: cp /home/ubuntu/mysql-connector-j-9.1.0.jar /opt/hive/lib/
    - name: Copy hive-site.xml to instances
      copy:
        src: etc/hive-site.xml
        dest: /opt/hive/conf/hive-site.xml
    - name: Copy hive-env.sh to instances
      copy:
        src: etc/hive-env.sh
        dest: /opt/hive/conf/hive-env.sh
    - name: Set JAVA_HOME based on architecture
      set_fact:
        java_home_path: "{{ '/usr/lib/jvm/java-8-openjdk-amd64' if ansible_architecture == 'x86_64' else '/usr/lib/jvm/java-8-openjdk-arm64' }}"
    - name: Append JAVA_HOME to hive-env.sh
      lineinfile:
        path: /opt/hive/conf/hive-env.sh
        line: "{{ item }}"
        state: present
      loop:
        - 'export JAVA_HOME={{ java_home_path }}'
    - name: Create log directory
      ansible.builtin.file:
        path: /opt/hive/logs
        state: directory
        mode: '0755'